export const SUPPORTED_SELLER_PERMISSION_IDS = new Set<string>([
  'clientes.visualizar',
  'clientes.criar',
  'clientes.editar',
  'clientes.excluir',
  'vendas.visualizar',
  'vendas.criar',
  'vendas.editar',
  'vendas.excluir',
  'relatorios.visualizar',
  'contacorrente.visualizar',
  'contacorrente.criar',
  'contacorrente.editar',
  'contacorrente.excluir',
  'produtos.visualizar',
  'produtos.criar',
  'produtos.editar',
  'produtos.excluir',
  'comissoes.visualizar',
  'comissoes.lancamentos.editar',
  'comissoes.lancamentos.excluir',
])

export const SUPPORTED_BACKOFFICE_PERMISSION_IDS = new Set<string>([
  ...SUPPORTED_SELLER_PERMISSION_IDS,
  'clientes.todos',
  'clientes.aprovar',
  'vendas.todas',
  'relatorios.todos',
  'config.minhas_empresas',
  'config.geral',
  'usuarios.visualizar',
  'usuarios.criar',
  'usuarios.editar',
  'usuarios.excluir',
  'usuarios.permissoes',
  'configuracoes.editar',
  'configuracoes.excluir',
  // Gating de página (permissões valem para backoffice)
  'equipe.visualizar',
  'metas.visualizar',
  'configuracoes.visualizar',
])
