-- ============================================================================
-- Migration 083: Tabelas para Gestão de Comissões e Pagamentos
-- ============================================================================
-- Descrição: 
-- Cria tabelas para lançamentos manuais, registros de pagamentos e 
-- controle de fechamento de períodos de comissão.
-- Data: 2026-02-06
-- ============================================================================

-- 1. Tabela para Lançamentos Manuais (Crédito/Débito)
CREATE TABLE IF NOT EXISTS public.lancamentos_comissao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendedor_uuid UUID NOT NULL REFERENCES auth.users(id),
    data_lancamento DATE NOT NULL DEFAULT CURRENT_DATE,
    tipo TEXT NOT NULL CHECK (tipo IN ('credito', 'debito')),
    valor NUMERIC(15, 2) NOT NULL,
    descricao TEXT NOT NULL,
    periodo TEXT NOT NULL, -- Formato YYYY-MM
    criado_por UUID REFERENCES auth.users(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Índices para lancamentos_comissao
CREATE INDEX IF NOT EXISTS idx_lancamentos_comissao_vendedor ON public.lancamentos_comissao(vendedor_uuid);
CREATE INDEX IF NOT EXISTS idx_lancamentos_comissao_periodo ON public.lancamentos_comissao(periodo);

-- RLS para lancamentos_comissao
ALTER TABLE public.lancamentos_comissao ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Vendedores podem ver seus proprios lancamentos" ON public.lancamentos_comissao;
CREATE POLICY "Vendedores podem ver seus proprios lancamentos" 
    ON public.lancamentos_comissao FOR SELECT 
    USING (auth.uid() = vendedor_uuid);

DROP POLICY IF EXISTS "Backoffice pode ver todos lancamentos" ON public.lancamentos_comissao;
CREATE POLICY "Backoffice pode ver todos lancamentos" 
    ON public.lancamentos_comissao FOR SELECT 
    USING (
        EXISTS (
            SELECT 1 FROM public."user" 
            WHERE user_id = auth.uid() AND tipo = 'backoffice'
        )
    );

DROP POLICY IF EXISTS "Apenas Backoffice pode criar lancamentos" ON public.lancamentos_comissao;
CREATE POLICY "Apenas Backoffice pode criar lancamentos" 
    ON public.lancamentos_comissao FOR INSERT 
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM public."user" 
            WHERE user_id = auth.uid() AND tipo = 'backoffice'
        )
    );


-- 2. Tabela para Pagamentos de Comissão
CREATE TABLE IF NOT EXISTS public.pagamentos_comissao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendedor_uuid UUID NOT NULL REFERENCES auth.users(id),
    data_pagamento DATE NOT NULL DEFAULT CURRENT_DATE,
    valor NUMERIC(15, 2) NOT NULL,
    periodo TEXT NOT NULL, -- Período de referência (YYYY-MM)
    forma_pagamento TEXT NOT NULL,
    comprovante_url TEXT,
    observacoes TEXT,
    realizado_por UUID REFERENCES auth.users(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Índices para pagamentos_comissao
CREATE INDEX IF NOT EXISTS idx_pagamentos_comissao_vendedor ON public.pagamentos_comissao(vendedor_uuid);
CREATE INDEX IF NOT EXISTS idx_pagamentos_comissao_periodo ON public.pagamentos_comissao(periodo);

-- RLS para pagamentos_comissao
ALTER TABLE public.pagamentos_comissao ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Vendedores podem ver seus proprios pagamentos" ON public.pagamentos_comissao;
CREATE POLICY "Vendedores podem ver seus proprios pagamentos" 
    ON public.pagamentos_comissao FOR SELECT 
    USING (auth.uid() = vendedor_uuid);

DROP POLICY IF EXISTS "Backoffice pode ver todos pagamentos" ON public.pagamentos_comissao;
CREATE POLICY "Backoffice pode ver todos pagamentos" 
    ON public.pagamentos_comissao FOR SELECT 
    USING (
        EXISTS (
            SELECT 1 FROM public."user" 
            WHERE user_id = auth.uid() AND tipo = 'backoffice'
        )
    );

DROP POLICY IF EXISTS "Apenas Backoffice pode registrar pagamentos" ON public.pagamentos_comissao;
CREATE POLICY "Apenas Backoffice pode registrar pagamentos" 
    ON public.pagamentos_comissao FOR INSERT 
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM public."user" 
            WHERE user_id = auth.uid() AND tipo = 'backoffice'
        )
    );


-- 3. Tabela para Controle de Períodos
CREATE TABLE IF NOT EXISTS public.controle_comissao_periodo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendedor_uuid UUID NOT NULL REFERENCES auth.users(id),
    periodo TEXT NOT NULL, -- Formato YYYY-MM
    status TEXT NOT NULL DEFAULT 'aberto' CHECK (status IN ('aberto', 'fechado', 'pago')),
    saldo_anterior NUMERIC(15, 2) DEFAULT 0, -- Saldo trazido do mês anterior
    saldo_final NUMERIC(15, 2), -- Saldo calculado no momento do fechamento
    data_fechamento TIMESTAMP WITH TIME ZONE,
    fechado_por UUID REFERENCES auth.users(id),
    
    UNIQUE(vendedor_uuid, periodo)
);

-- Índices para controle_comissao_periodo
CREATE INDEX IF NOT EXISTS idx_controle_comissao_periodo_vendedor ON public.controle_comissao_periodo(vendedor_uuid);
CREATE INDEX IF NOT EXISTS idx_controle_comissao_periodo_periodo ON public.controle_comissao_periodo(periodo);

-- RLS para controle_comissao_periodo
ALTER TABLE public.controle_comissao_periodo ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Vendedores podem ver seus status de periodo" ON public.controle_comissao_periodo;
CREATE POLICY "Vendedores podem ver seus status de periodo" 
    ON public.controle_comissao_periodo FOR SELECT 
    USING (auth.uid() = vendedor_uuid);

DROP POLICY IF EXISTS "Backoffice pode gerenciar controle de periodos" ON public.controle_comissao_periodo;
CREATE POLICY "Backoffice pode gerenciar controle de periodos" 
    ON public.controle_comissao_periodo FOR ALL 
    USING (
        EXISTS (
            SELECT 1 FROM public."user" 
            WHERE user_id = auth.uid() AND tipo = 'backoffice'
        )
    );
