-- 085: Mapeamento de Natureza de Operacao por Empresa para Tiny ERP
-- Cada empresa (conta Tiny) pode exigir um valor diferente em <natureza_operacao>.

create table if not exists public.tiny_empresa_natureza_operacao (
  id bigint generated by default as identity primary key,
  empresa_id bigint not null references public.ref_empresas_subsidiarias(id),
  natureza_operacao_id bigint not null references public.natureza_operacao(id),
  tiny_valor text not null,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz null
);

create unique index if not exists uq_tiny_empresa_natureza_operacao_empresa_natureza
  on public.tiny_empresa_natureza_operacao (empresa_id, natureza_operacao_id);

create index if not exists idx_tiny_empresa_natureza_operacao_empresa_id
  on public.tiny_empresa_natureza_operacao (empresa_id);

create index if not exists idx_tiny_empresa_natureza_operacao_natureza_operacao_id
  on public.tiny_empresa_natureza_operacao (natureza_operacao_id);

alter table public.tiny_empresa_natureza_operacao enable row level security;

